import { HomeContainer } from './HomePage.styled';

export function HomePage() {
  return (
    <HomeContainer>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
      <p>Auto</p>
    </HomeContainer>
  );
}
